import type { Campaign, Creator } from "./types";

/* Mock data for the MVP presentation.
 * Realistic briefs and creators so the demo feels like a live marketplace.
 */

export const campaigns: Campaign[] = [
  {
    id: "c1",
    slug: "lumina-skin-rutina-skincare",
    title: "Rutina de skincare en 20 segundos",
    brand: "Lumina Skin",
    category: "Belleza",
    budget: 350,
    brief:
      "Buscamos micro-creadores que cuenten su rutina diaria de skincare en un video vertical dinámico. Queremos recomendaciones honestas, estilo 'así lo uso yo', con foco en la piel real y sin exageraciones.",
    requirements: [
      "Entre 20 y 35 años, con audiencia LATAM",
      "Mínimo 10 mil followers en Instagram o TikTok",
      "Tono cercano y honesto, no publicitario",
      "Entrega final en 7 días desde la selección",
    ],
    deliverables: [
      "1 video vertical de 15–30 segundos",
      "2 historias complementarias",
      "Derechos de uso por 6 meses",
      "Métricas y datos de alcance al cierre",
    ],
    platforms: ["Instagram", "TikTok"],
    deadline: "2026-09-15",
    publishedAt: "2026-08-20",
    applications: 34,
    slots: 3,
    status: "active",
  },
  {
    id: "c2",
    slug: "yerba-pampa-unboxing-mate",
    title: "Unboxing de nuestro nuevo mate",
    brand: "Yerba Pampa",
    category: "Gastronomía",
    budget: 280,
    brief:
      "Queremos que abras nuestro nuevo kit de mate frente a cámara. Mostrá el diseño, el aroma y tu primera cebada. Autenticidad total: si algo no te gusta, decilo igual.",
    requirements: [
      "Audiencia de Argentina o Uruguay",
      "Experiencia previa con contenido gastronómico",
      "Formato unboxing o 'primeras impresiones'",
      "Entrega en 10 días desde la recepción del kit",
    ],
    deliverables: [
      "1 video vertical de 30–45 segundos",
      "1 post en feed con fotos reales",
      "Derechos de uso por 12 meses",
      "Keyword y hashtags de la campaña",
    ],
    platforms: ["Instagram", "TikTok"],
    deadline: "2026-09-22",
    publishedAt: "2026-08-25",
    applications: 21,
    slots: 2,
    status: "closing",
  },
  {
    id: "c3",
    slug: "atelier-norte-outfit-capsula",
    title: "Outfit de invierno con nuestra línea cápsula",
    brand: "Atelier Norte",
    category: "Moda",
    budget: 420,
    brief:
      "Presentamos nuestra línea cápsula de invierno. Buscamos creadores de moda que armen looks versátiles con 3 prendas y los muestren en situaciones reales: la calle, la oficina, un plan nocturno.",
    requirements: [
      "Estilo personal definido en el feed",
      "Mínimo 8 mil followers",
      "Profesionalidad y buena calidad de edición",
      "Coherencia estética con la marca",
    ],
    deliverables: [
      "1 reel principal de 30 segundos",
      "3 fotos de lookbook en alta resolución",
      "1 historia con el proceso de armado",
      "Licencia de uso indefinida (media)",
    ],
    platforms: ["Instagram"],
    deadline: "2026-09-30",
    publishedAt: "2026-08-18",
    applications: 18,
    slots: 2,
    status: "active",
  },
  {
    id: "c4",
    slug: "flexio-setup-home-office",
    title: "Tu setup de home office ergonómico",
    brand: "Flexio",
    category: "Tecnología",
    budget: 380,
    brief:
      "Que muestres cómo transformaste tu escritorio con nuestros soportes ergonómicos. El foco está en la productividad: antes/después, comodidad y orden visual.",
    requirements: [
      "Audiencia tech, productividad o estudio",
      "Cámara y edición de calidad media-alta",
      "Mínimo 5 mil followers",
      "Entrega en 8 días desde la selección",
    ],
    deliverables: [
      "1 video vertical de 30–45 segundos (antes/después)",
      "Toma b-roll de 15 segundos libre de uso",
      "Derechos de uso por 6 meses",
      "Reporte de métricas al cierre",
    ],
    platforms: ["TikTok", "YouTube", "Instagram"],
    deadline: "2026-09-10",
    publishedAt: "2026-08-22",
    applications: 29,
    slots: 1,
    status: "closing",
  },
  {
    id: "c5",
    slug: "olivia-receta-aceite-oliva",
    title: "Receta fácil con nuestro aceite de oliva",
    brand: "Olivia",
    category: "Gastronomía",
    budget: 250,
    brief:
      "Una receta simple (pasta, ensalada o tostada) protagonizada por nuestro aceite de oliva extra virgen. Queremos cocina casera, luz natural y cero producción exagerada.",
    requirements: [
      "Audiencia food o lifestyle",
      "Receta propia y original",
      "Entrega en 12 días desde la selección",
      "Captura de pantalla del resultado final",
    ],
    deliverables: [
      "1 video vertical de 30–60 segundos",
      "1 foto del plato terminado",
      "Derechos de uso por 6 meses",
    ],
    platforms: ["TikTok", "Instagram"],
    deadline: "2026-10-05",
    publishedAt: "2026-08-27",
    applications: 15,
    slots: 4,
    status: "active",
  },
  {
    id: "c6",
    slug: "nucleo-fit-entrena-casa",
    title: "Entrená en casa: 3 ejercicios con mancuernas",
    brand: "Núcleo Fit",
    category: "Fitness",
    budget: 300,
    brief:
      "Armá una rutina de 3 ejercicios con mancuernas que se pueda hacer en 15 minutos. Priorizamos creadores fitness que transmitan energía y técnica limpia.",
    requirements: [
      "Presencia en nicho fitness o bienestar",
      "Mínimo 7 mil followers",
      "Formato demo + tips cortos",
      "Entrega en 9 días desde la selección",
    ],
    deliverables: [
      "1 video vertical de 30–45 segundos",
      "2 historias de proceso",
      "Licencia de uso por 6 meses",
      "Métricas de alcance al cierre",
    ],
    platforms: ["Instagram", "TikTok"],
    deadline: "2026-09-18",
    publishedAt: "2026-08-24",
    applications: 25,
    slots: 2,
    status: "active",
  },
];

export const creators: Creator[] = [
  {
    id: "cr1",
    name: "Valentina Ríos",
    handle: "@valen.rios",
    niche: "Skincare & belleza",
    city: "Buenos Aires",
    followers: 128_000,
    rating: 4.9,
    reviews: 212,
    tags: ["skincare", "reseñas honestas", "tutoriales"],
    ratePerVideo: 150,
    completedDeals: 86,
    verified: true,
    bio: "Dermatologista amateur y fanática del skincare real. Más de 200 colaboraciones con marcas que creen en la honestidad.",
  },
  {
    id: "cr2",
    name: "Franco Maidana",
    handle: "@francomaida.fit",
    niche: "Fitness & entrenamiento",
    city: "Rosario",
    followers: 86_000,
    rating: 4.7,
    reviews: 148,
    tags: ["entrenamiento", "ejercicios en casa", "motivación"],
    ratePerVideo: 120,
    completedDeals: 54,
    verified: true,
    bio: "Entrenador personal. Demuestro que el gimnasio no es obligación: se puede entrenar fuerte en cualquier lado.",
  },
  {
    id: "cr3",
    name: "Sofía Benítez",
    handle: "@sofi.enlacocina",
    niche: "Cocina & gastronomía",
    city: "Mendoza",
    followers: 64_000,
    rating: 4.8,
    reviews: 173,
    tags: ["recetas fáciles", "cocina casera", "vino y oliva"],
    ratePerVideo: 110,
    completedDeals: 67,
    verified: false,
    bio: "Cocino como en casa de mi abuela pero con tips para el día a día. Recetas simples, ingredientes reales.",
  },
  {
    id: "cr4",
    name: "Julián Pereyra",
    handle: "@juli.tech",
    niche: "Tecnología & unboxing",
    city: "Córdoba",
    followers: 210_000,
    rating: 4.6,
    reviews: 301,
    tags: ["unboxing", "reviews", "setup"],
    ratePerVideo: 190,
    completedDeals: 132,
    verified: true,
    bio: "Unboxings sin libreto. Si un producto es malo, te lo digo. 130+ colaboraciones y ninguna reseña comprada.",
  },
  {
    id: "cr5",
    name: "Martina López",
    handle: "@martu.outfits",
    niche: "Moda & estilo",
    city: "Buenos Aires",
    followers: 47_000,
    rating: 5.0,
    reviews: 98,
    tags: ["outfits", "moda sustentable", "lookbook"],
    ratePerVideo: 130,
    completedDeals: 41,
    verified: true,
    bio: "Estilo real para presupuestos reales. Lookbook callejero y moda con conciencia.",
  },
  {
    id: "cr6",
    name: "Tomás Corral",
    handle: "@tomi.lifestyle",
    niche: "Lifestyle & familia",
    city: "Mar del Plata",
    followers: 95_000,
    rating: 4.8,
    reviews: 187,
    tags: ["vida real", "familia", "día a día"],
    ratePerVideo: 115,
    completedDeals: 73,
    verified: false,
    bio: "Contenido de la vida como es: rutina, familia y momentos simples. Marcas reales, personas reales.",
  },
];